version: "3"
services:
  discovery:
    image: saltfish/discovery
    restart: always
    ports:
      - "8761:8080"

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "15672:15672"

  config-server:
    image: saltfish/config-server
    restart: always
    ports:
      - "9000:8080"
    links:
      - discovery

  hello-service:
    image: saltfish/hello-service
    ports:
      - "8080:8080"
    restart: always
    links:
      - discovery
      - config-server

  hello-service2:
    image: saltfish/hello-service
    ports:
      - "8081:8080"
    restart: always
    links:
      - discovery
      - config-server

  feign:
    image: saltfish/feign
    ports:
      - "8082:8080"
    restart: always
    links:
      - discovery
      - config-server
      - hello-service
      - hello-service2

  config-client:
    image: saltfish/config-client
    ports:
      - "8083:8080"
    restart: always
    links:
      - discovery
      - config-server
      - rabbitmq