version: "3"
services:
  discovery:
    image: saltfish/discovery
    restart: always
    ports:
      - "8761:8080"

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  config-server:
    image: saltfish/config-server
    restart: always
    ports:
      - "9000:8080"
    links:
      - discovery
      - rabbitmq