version: "3"
services:
  discovery:
    image: saltfish/discovery
    restart: always
    ports:
      - "8761:8080"

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"

  config-server:
    image: saltfish/config-server
    restart: always
    ports:
      - "9000:8080"
    links:
      - discovery
      - rabbitmq

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456

  user-center:
    image: saltfish/user-center
    restart: always
    ports:
      - "8081:8080"
    links:
      - discovery
      - config-server
      - rabbitmq
      - mysql

  wechat-core:
    image: saltfish/wechat-core
    restart: always
    ports:
      - "8082:8080"
    links:
      - discovery
      - config-server
      - rabbitmq
      - mysql
      - user-center

  gateway:
      image: saltfish/gateway
      restart: always
      ports:
        - "8080:8080"
      links:
        - discovery
        - config-server
        - rabbitmq

  zipkin:
    image: saltfish/zipkin
    restart: always
    ports:
      - "9411:8080"
    links:
      - discovery