spring:
  application:
    name: config-client
  cloud:
    config:
      uri: http://config-server:8080
      label: master
      profile: dev
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8080/eureka
server:
  port: 8080