spring:
  application:
    name: hello-service
  cloud:
    config:
      discovery:
        service-id: config-server
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8080/eureka
server:
  port: 8080