spring:
  rabbitmq:
#    host: rabbitmp
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh,refresh