# api 服务网关路由配置
#zuul:
#  routes:
#    wechat:
#      path: /wechat/**
#      serviceId: wechat-core
zuul:
  routes:
    wechat:
      path: /wechat/**
      serviceId: wechat-core
    demo:
      path: /demo/**
      serviceId: wechat-demo
  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
# 设置允许延迟时间为10s
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
wechat:
  token: woshijiangtianxing
  msg:
    path: /demo/index