# api 服务网关路由配置
#zuul:
#  routes:
#    wechat:
#      path: /wechat/**
#      serviceId: wechat-core
zuul:
  routes:
    wechat:
      path: /wechat/**
      serviceId: wechat-service
  filter:
    authHeader:
      exclude: get:/wechat/access_token, get:/wechat/token,
# 设置允许延迟时间为10s
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000