#spring:
## 数据源配置
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: "jdbc:mysql://mysql:3306/user_center?useUnicode=true&characterEncoding=UTF-8&useTimezone=true&serverTimezone=PRC&useSSL=false"
#    username: root
#    password: 123456
#    initialSize: 2
#    maxActive: 20
#    minIdle: 0
#    maxWait: 60000

spring:
# 数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/user_center?useUnicode=true&characterEncoding=UTF-8&useTimezone=true&serverTimezone=PRC&useSSL=false"
    username: root
    password: 123456
    initialSize: 2
    maxActive: 20
    minIdle: 0
    maxWait: 60000