# api 服务网关路由配置
zuul:
  routes:
    wechat:
      path: /wechat/**
      serviceId: wechat-core
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000