spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:jx3536/saltfish
          search-paths: config
          clone-on-start: true
          passphrase: jiangtianxing
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8080/eureka
  instance:
    prefer-ip-address: false