spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:jx3536/spring-cloud-config
          search-paths: respo
          clone-on-start: true
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8080/eureka
  instance:
    prefer-ip-address: false