spring:
  application:
    name: discovery
  security:
    user:
      name: jiangtianxing
      password: jiangtianxing
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: discovery
server:
  port: 8080
management:
  endpoint:
    health:
      show-details: always